//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team9SimpleJira
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int IssueId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public int Priority { get; set; }
        public byte[] Photo { get; set; }
        public string Category { get; set; }
        public string Status { get; set; }
        public int OwnerId { get; set; }
        public int UserStoryId { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserStory UserStory { get; set; }
    }
}
