//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team9SimpleJira
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprint
    {
        public int SprintId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Status { get; set; }
        public int ProjectId { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Team Team { get; set; }
    }
}
